name: Trigger auto deployment for container-app-pizizgzgy4pdm

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-pizizgzgy4pdm-AutoDeployTrigger-74c35e33-8ee8-4650-a6d4-4d5702d0a052.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPPIZIZGZGY4PDM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPPIZIZGZGY4PDM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPPIZIZGZGY4PDM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrypizizgzgy4pdm.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPPIZIZGZGY4PDM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPPIZIZGZGY4PDM_REGISTRY_PASSWORD }}
          containerAppName: container-app-pizizgzgy4pdm
          resourceGroup: markspacecolorsapi
          imageToBuild: containerregistrypizizgzgy4pdm.azurecr.io/container-app-pizizgzgy4pdm:${{ github.sha }}
          dockerfilePath: Dockerfile


